
stages:
  - lint
  - test

variables:
  RUBY_VERSION: '4.0'

.base:
  needs: []
  image: ruby:${RUBY_VERSION}-trixie
  variables:
    GIT_DEPTH: "1"
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_PATHS: task
    RUBYOPT: --enable-frozen-string-literal

.test:
  extends: .base
  stage: test
  before_script:
    - bundle install --retry=3
    - unset CI # Coverage doesn't work well with frozen literal
  script:
    - ruby -vr bundler/setup -S rake test

.with-specific-rack:
  variables:
    RACK_VERSION: 3.1.16

rubocop:
  extends: .base
  stage: lint
  before_script:
    - gem install rubocop
  script:
    - rubocop

ruby:3.4:
  extends: .test
  variables:
    RUBY_VERSION: '3.4'

ruby:4.0:
  extends: .test
  variables:
    RUBY_VERSION: '4.0'

ruby:3.4-with-specific-rack:
  extends:
    - ruby:3.4
    - .with-specific-rack

ruby:4.0-with-specific-rack:
  extends:
    - ruby:4.0
    - .with-specific-rack
